config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items do
    member do
      post :complete
      # post :uncomplete
    end
  end
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :title, :description, :user_id

  belongs_to :user

  def completed?
    completed_at.present?
    # !completed_at.blnck?
    # 沒驚嘆號代表是空的話就顯示ture
    # 加驚嘆號代表不是空的話(裡面有東西)就顯示ture
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy] 

  def index
    @items = Item.where(:user_id => current_user.id ).order(completed_at: :asc) if user_signed_in?
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:notice] = 'Todo was created'
      redirect_to @item
    else
      flash[:alert] = 'Not create'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      flash[:notice] = 'Todo was update'
      redirect_to @item
    else
      flash[:alert] = 'Not update'
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  def complete
    @item = Item.find(params[:id])
    if @item.completed?
       # @item.update_attribute(:completed_at, nil)
       @item.update({completed_at: nil})
       # 如果completed_at 有值，把質變nil
    else
       @item.update_attribute(:completed_at, Time.now)
     #如果completed_at 沒有值，把Time.now加進去
    end
    redirect_to root_path
  end

  # def uncomplete
  #   @item = Item.find(params[:id])
  #   @item.update.attribute(:updated_at)
  #   redirect_to root_path
  # end



  private

    def find_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title, :description, :user_id)
    end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<% if item.errors.any? %>
  <ul>
    <% item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for item do |f| %>
  
  <%= f.label :'Item Title' %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>

<% end %>

app/views/items/_welcome.html.erb
<div class="jumbotron">
  <h2>Hiptime! Free and Easy.</h2>
  <br>
  <h4>Trusted by Millions. Hiptime is th best online Tesk Manegement App!</h4>
  <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-danger' %>
</div>

app/views/items/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <%= render partial: 'form', locals: { item: @item } %>
</div>

app/views/items/index.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    
    <% if user_signed_in? %>

      <% @items.each do |item| %>

      <div class="index-wrapper">
        <% if item.completed? %>
        <!-- 如果completed資料裡有東西代表完成 ，就把item顯示以下排版-->
<!-- Item completed -->
          <div class="row item">
            <div class="col-md-2">
              <p><%= link_to complete_item_path(item), method: :post, data: {confirm: 'Make Item back to tesk '} do %></p>
                <i class="glyphicon glyphicon-ok"></i>
              <% end %>
            </div>
            <div class="col-md-2">
              <p><%= link_to item, method: :delete, data: {confirm: 'Are you sure?'} do %></p>
               <i class="glyphicon glyphicon-trash"></i>
               <% end %>
            </div>
            <div class="col-md-8">
              <h2 style="opacity: 0.5;" class="item-title"><strike><%= link_to item.title, item_path(item) %></strike></h2>
              <p style="opacity: 0.5;" class="item-sub-title item-desc"><%= item.description %></p>
              <p style="opacity: 0.5;" class="item-created-atitem-sub-title">Completed <%= time_ago_in_words(item.completed_at) %> ago</p>
              <p>Update <%= time_ago_in_words(item.updated_at) %></p>
            </div>
          </div>

        <% else %>
<!-- Item  NOT Completed -->

          <div class="row item">
            <div class="col-md-2">
              <p><%= link_to complete_item_path(item), method: :post, data: {confirm: 'Are you completed?'} do %></p>
                <i class="glyphicon glyphicon-ok"></i>
              <% end %>
            </div>
            <div class="col-md-8">
              <h2 class="item-title"><%= link_to item.title, item_path(item) %></h2>
              <p class="item-sub-title item-desc"><%= item.description %></p>
              <p style="opacity: 0.5;" class="item-created-atitem-sub-title">Created <%= time_ago_in_words(item.created_at) %> ago</p>
              <p>Update <%= time_ago_in_words(item.updated_at) %></p>
            </div>
            <div class="col-md-2">
              <p><%= link_to item, method: :delete, data: {confirm: 'Are you sure?'} do %></p>
               <i class="glyphicon glyphicon-trash"></i>
               <% end %>
            </div>
          </div>

        <% end %>
      </div>

        
      <% end %>
      <!-- item.each的end  -->

    <% else %>
        <%= render 'welcome' %>
     <% end %>

  </div>
</div>

app/views/items/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <%= render partial: 'form', locals: { item: @item } %>
</div>

app/views/items/show.html.erb
<div class="col-md-10 col-md-offset-1">
  
  <h2><%= @item.title %></h2>
  <p><%= @item.description %></p>

  <div class="col-md-4 col-md-offset-4">
    <%= link_to 'Back', items_path %>
    <% if user_signed_in? %> 
      | <%= link_to 'edit', edit_item_path(@item) %> |
      <%= link_to 'Trash it', item_path(@item), method: :delete, data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hiptime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Hiptime', items_path, class: 'navbar-brand' %> 
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user.present? %>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <%= link_to 'Create Item', new_item_path, class: 'navbar-text navbar-link' %>
        <% end %>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>